{{- if and .Values.guardrails.enabled .Values.guardrails.maasApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: maas-api-key
  namespace: {{ include "guardrails.namespace" . }}
  labels:
    {{- include "guardrails.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.guardrails.maasApiKey | quote }}
{{- end }}
