# OpenShell Helm chart overrides for OpenShift Container Platform, WITHOUT
# OIDC (unauthenticated CLI access — used when WITH_OIDC=false).
#
# Kept as an explicit, standalone file rather than generated by stripping the
# `oidc:` block out of values-ocp.yaml.tpl at deploy time (`sed` block-delete
# is fragile against reindentation/reordering of that file) — see
# scripts/deploy-openshell.sh. Keep the non-`oidc`/`auth` sections of this
# file in sync with values-ocp.yaml.tpl by hand if you change one.
#
# Template: __APPS_DOMAIN__ is replaced at deploy time by scripts/common.sh render_template().

replicaCount: 1

workload:
  kind: statefulset

image:
  tag: "0.0.83"

supervisor:
  image:
    tag: "0.0.83"

# Let OpenShift SCC admission assign UIDs and fsGroup
podSecurityContext:
  fsGroup: null

securityContext:
  runAsUser: null

# PKI init job creates openshell-server-tls, openshell-client-tls,
# and openshell-jwt-keys secrets automatically on first install.
# mTLS is required for SSH relay, sandbox exec, and credential injection.
pkiInitJob:
  serverDnsNames:
    - "openshell-gw-openshell.__APPS_DOMAIN__"
    - "*.__APPS_DOMAIN__"

server:
  auth:
    allowUnauthenticatedUsers: true
