# No-OIDC overlay (unauthenticated CLI access — used when WITH_OIDC=false).
#
# Kept as an explicit, standalone file rather than generated by stripping the
# `oidc:` block out of values-ocp.yaml.tpl at deploy time (`sed` block-delete
# is fragile against reindentation/reordering of that file) — see
# scripts/deploy-openshell.sh. Keep the non-oidc/auth sections of this file
# in sync with values-ocp.yaml.tpl by hand if you change one.
#
# Template: __APPS_DOMAIN__ is replaced at deploy time by scripts/common.sh
# render_template() (unused in this particular overlay today, kept for
# parity/future-proofing since both overlays are rendered the same way).

openshell:
  server:
    auth:
      allowUnauthenticatedUsers: true
